<?php

/**
 * Eloquent class to describe the bairros table
 *
 * automatically generated by ModelGenerator.php
 */
class Bairro extends Eloquent{
    protected $table = 'bairros';

    public $timestamps = false;

    protected $fillable = array('nome');
}
