<?php

/**
 * Eloquent class to describe the cidades table
 *
 * automatically generated by ModelGenerator.php
 */
class Cidade extends Eloquent{
    protected $table = 'cidades';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function estado(){
        return $this->belongsTo('Estado', 'estado_id', 'id');
    }
}
