<?php


/**
 * Eloquent class to describe the contatos table
 *
 * automatically generated by ModelGenerator.php
 */
class Contato extends Eloquent{
    protected $table = 'contatos';

    public $timestamps = false;

    protected $fillable = array('telefone', 'celular', 'fax', 'email');

}
