<?php 

/**
 * Eloquent class to describe the destinos table
 *
 * automatically generated by ModelGenerator.php
 */
class Destino extends Eloquent{
    protected $table = 'destinos';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->hasMany('Viagem', 'destino_id', 'id');
    }
}
