<?php 

/**
 * Eloquent class to describe the estados table
 *
 * automatically generated by ModelGenerator.php
 */
class Estado extends Eloquent{
    protected $table = 'estados';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function cidades(){
        return $this->hasMany('Cidade', 'estado_id', 'id');
    }
}
