<?php 

/**
 * Eloquent class to describe the estacionamentos table
 *
 * automatically generated by ModelGenerator.php
 */
class Estacionamento extends Eloquent{
    protected $table = 'estacionamentos';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->hasMany('Viagem', 'estacionamento_id', 'id');
    }
}
