<?php 

/**
 * Eloquent class to describe the organizacoes table
 *
 * automatically generated by ModelGenerator.php
 */
class Organizacao extends Eloquent{
    protected $table = 'organizacoes';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->hasMany('Viagem', 'organizacao_id', 'id');
    }
}
