<?php 

/**
 * Eloquent class to describe the tipos_visitantes table
 *
 * automatically generated by ModelGenerator.php
 */
class TipoVisitante extends Eloquent{
    protected $table = 'tipos_visitantes';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->belongsToMany('Viagens', 'viagens_visitantes', 'tipo_visitante_id', 'viagem_id');
    }
}
