<?php 

/**
 * Eloquent class to describe the tipos_veiculos table
 *
 * automatically generated by ModelGenerator.php
 */
class TipoVeiculo extends Eloquent{
    protected $table = 'tipos_veiculos';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function veiculos(){
        return $this->hasMany('Veiculo', 'tipo_veiculo_id', 'id');
    }
}
