<?php 

/**
 * Eloquent class to describe the tipos_motivos table
 *
 * automatically generated by ModelGenerator.php
 */
class TipoMotivo extends Eloquent{
    protected $table = 'tipos_motivos';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->belongsToMany('Viagem', 'viagens_motivos', 'tipo_motivo_id', 'viagem_id');
    }
}
