<?php 

/**
 * Eloquent class to describe the destinos table
 *
 * automatically generated by ModelGenerator.php
 */
class TipoDestino extends Eloquent{
    protected $table = 'tipos_destinos';

    public $timestamps = false;

    protected $fillable = array('nome');

    public function viagens(){
        return $this->belongsToMany('Viagem', 'viagens_destinos', 'tipo_destino_id', 'viagem_id');
    }
}
