<?php 

/**
 * Eloquent class to describe the usuarios table
 *
 * automatically generated by ModelGenerator.php
 */
class Usuarios extends Eloquent{
    protected $table = 'usuarios';

    protected $fillable = array('nome', 'login', 'password', 'remember_token', 'deleted_at');


}
