<?php 

/**
 * Eloquent class to describe the veiculos table
 *
 * automatically generated by ModelGenerator.php
 */
class Veiculo extends Eloquent{
    protected $table = 'veiculos';

    public $timestamps = false;

    protected $fillable = array('placa', 'registro','anexo');

    public function tipo(){
        return $this->belongsTo('TipoVeiculo', 'tipo_veiculo_id', 'id');
    }

    public function viagem(){
        return $this->belongsTo('Viagem', 'viagem_id', 'id');
    }
}
