<?php 

/**
 * Eloquent class to describe the viagens_atrativos table
 *
 * automatically generated by ModelGenerator.php
 */
class ViagemAtrativo extends Eloquent{
    protected $table = 'viagens_atrativos';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('especificar');

    public function tipoAtrativo(){
        return $this->belongsTo('TipoAtrativo', 'tipos_atrativos_id', 'id');
    }

    public function viagem(){
        return $this->belongsTo('Viagem', 'viagens_id', 'id');
    }
}
