<?php 

/**
 * Eloquent class to describe the viagens table
 *
 * automatically generated by ModelGenerator.php
 */
class Viagem extends Eloquent{
    protected $table = 'viagens';

    protected $fillable = array('numeroPessoas', 'chegada', 'saida', 'primeira_vez', 'local_destino', 'anexo',
        'roteiro_predefinido', 'roteiro_especificar');

    public function cidade_origem(){
        return $this->belongsTo('Cidade', 'cidade_origem', 'id');
    }

    public function cidade_destino(){
        return $this->belongsTo('Cidade', 'cidade_destino', 'id');
    }

    public function destino(){
        return $this->belongsTo('Destino', 'destino_id', 'id');
    }

    public function organizacao(){
        return $this->belongsTo('Organizacao', 'organizacao_id', 'id');
    }

    public function pessoa(){
        return $this->belongsTo('Pessoa', 'pessoa_id', 'id');
    }

    public function quantidadeVez(){
        return $this->belongsTo('QuantidadeVez', 'quantidade_vezes_id', 'id');
    }

    public function veiculos(){
        return $this->hasMany('Veiculo', 'viagem_id', 'id');
    }

    public function tiposAtrativos(){
        return $this->belongsToMany('TipoAtrativo', 'viagens_atrativos', 'viagens_id', 'tipos_atrativos_id');
    }

    public function tiposMotivos(){
        return $this->belongsToMany('TipoMotivo', 'viagens_motivos', 'viagens_id', 'tipos_motivos_id');
    }

    public function tiposRefeicoes(){
        return $this->belongsToMany('TipoRefeicao', 'viagens_refeicoes', 'viagens_id', 'tipos_refeicoes_id');
    }

    public function tiposVisitantes(){
        return $this->belongsToMany('TipoVisitante', 'viagens_visitantes', 'viagens_id', 'tipos_visitantes_id');
    }
}
