<?php 

/**
 * Eloquent class to describe the viagens_motivos table
 *
 * automatically generated by ModelGenerator.php
 */
class ViagemMotivo extends Eloquent{
    protected $table = 'viagens_motivos';
    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('especificar');

    public function tipoMotivo(){
        return $this->belongsTo('TipoMotivo', 'tipos_motivos_id', 'id');
    }

    public function viagem(){
        return $this->belongsTo('Viagem', 'viagens_id', 'id');
    }
}
