<?php 

/**
 * Eloquent class to describe the viagens table
 *
 * automatically generated by ModelGenerator.php
 */
class Viagem extends Eloquent{
    protected $table = 'viagens';

    protected $fillable = array('cidade_origem','bairro_id','numeroPessoas', 'chegada', 'saida', 'primeira_vez', 'local_destino', 'anexo',
        'roteiro_predefinido', 'roteiro_especificar','sugestao','organizacao_id', 'destino_id','quantidade_vez_id', 'empresa_veiculo');

    public function cidade_origem(){
        return $this->belongsTo('Cidade', 'cidade_origem', 'id');
    }

    public function empresa(){
        return $this->belongsTo('Empresa', 'empresa_id', 'id');
    }

    public function cidade_destino(){
        return $this->belongsTo('Cidade', 'cidade_destino', 'id');
    }

    public function destino(){
        return $this->belongsTo('Destino', 'destino_id', 'id');
    }

    public function organizacao(){
        return $this->belongsTo('Organizacao', 'organizacao_id', 'id');
    }

    public function pessoa(){
        return $this->belongsTo('Pessoa', 'pessoa_id', 'id');
    }

    public function quantidadeVez(){
        return $this->belongsTo('QuantidadeVez', 'quantidade_vez_id', 'id');
    }

    public function veiculos(){
        return $this->hasMany('Veiculo', 'viagem_id', 'id');
    }

    public function tiposAtrativos(){
        return $this->belongsToMany('TipoAtrativo', 'viagens_atrativos', 'viagem_id', 'tipo_atrativo_id');
    }

    public function tiposMotivos(){
        return $this->belongsToMany('TipoMotivo', 'viagens_motivos', 'viagem_id', 'tipo_motivo_id');
    }

    public function tiposRefeicoes(){
        return $this->belongsToMany('TipoRefeicao', 'viagens_refeicoes', 'viagem_id', 'tipo_refeicao_id');
    }

    public function tiposVisitantes(){
        return $this->belongsToMany('TipoVisitante', 'viagens_visitantes', 'viagem_id', 'tipo_visitante_id');
    }

    public function tiposDestinos(){
        return $this->belongsToMany('TipoDestino', 'viagens_destinos', 'viagem_id', 'tipo_destino_id');
    }

    public function setChegadaAttribute($chegada){
        $this->attributes['chegada'] = FormatterHelper::brToEnDate($chegada);
    }
    
    public function getChegadaAttribute(){
        return FormatterHelper::enToBrDate($this->attributes['chegada']);
    }

    public function setSaidaAttribute($saida){
        $this->attributes['saida'] = FormatterHelper::brToEnDate($saida);
    }
    
    public function getSaidaAttribute(){
        return FormatterHelper::enToBrDate($this->attributes['saida']);
    }
}
