<?php 

/**
 * Eloquent class to describe the viagens_refeicoes table
 *
 * automatically generated by ModelGenerator.php
 */
class ViagemRefeicao extends Eloquent{
    protected $table = 'viagens_refeicoes';

    public $timestamps = false;

    protected $fillable = array('especificar');

    public function tipoRefeicao(){
        return $this->belongsTo('TipoRefeicao', 'tipos_refeicoes_id', 'id');
    }

    public function viagem(){
        return $this->belongsTo('Viagem', 'viagens_id', 'id');
    }
}
