<?php 

/**
 * Eloquent class to describe the viagens_visitantes table
 *
 * automatically generated by ModelGenerator.php
 */
class ViagemVisitante extends Eloquent{
    protected $table = 'viagens_visitantes';

    public $timestamps = false;

    protected $fillable = array('especificar');

    public function tipoVisitante(){
        return $this->belongsTo('TipoVisitante', 'tipos_visitantes_id', 'id');
    }

    public function viagem(){
        return $this->belongsTo('Viagem', 'viagens_id', 'id');
    }
}
